
on: 
  push:
    branches: 
      - main
    paths:
      - "bend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install Dependencies
        run: |
          cd bend
          npm ci
          npm test